# Generated by Django 3.0.6 on 2020-07-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200623_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='data_id',
        ),
    ]
