# Generated by Django 3.0.6 on 2020-07-05 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200705_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='href',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
