# Generated by Django 3.0.6 on 2020-07-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_id',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='href',
        ),
    ]
