# Generated by Django 3.0.6 on 2020-07-22 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200722_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_fl',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
